_delete_cmf_resource:
    path: /api/{repositoryName}/{path}
    methods: ['delete']
    requirements:
        path: .*
    defaults:
        _controller: cmf_resource_rest.controller.resource:deleteResourceAction
        _format: json

_patch_cmf_resource:
    path: /api/{repositoryName}/{path}
    methods: ['patch']
    requirements:
        path: .*
    defaults:
        _controller: cmf_resource_rest.controller.resource:patchResourceAction
        _format: json

_get_cmf_resource:
    path: /api/{repositoryName}/{path}
    methods: ['get']
    requirements:
        path: .*
    defaults:
        _controller: cmf_resource_rest.controller.resource:getResourceAction
        _format: json
